modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="zombieawareness"
version="${file.jarVersion}"
displayName="zombieawareness"
authors="Corosus"
description='''
They smellz
'''

[[mods]]
modId="modconfig"
version="${file.jarVersion}"
displayName="modconfig"
authors="Corosus"
description='''

'''